version: 1.0.{build}

image: Visual Studio 2019

cache:
  - IPC\packages -> **\packages.config

# Use custom 'clone_script' instead of 'install' in order to run it before the cache from submodule is restored.
clone_script:
  - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
  - git submodule update --init
  - cd bond
  - git submodule update --init thirdparty\rapidjson
  - cd ..

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BUILD_PATH: $(platform)\$(configuration)

install:
  - nuget restore IPC.Bond.sln

matrix:
  fast_finish: true

before_build:
  - bond.cmd %configuration% "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild IPC\IPC.sln /p:Configuration=%configuration% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  project: IPC.Bond.sln

test:
  assemblies:
  - $(BUILD_PATH)\IPC.Bond.Managed.UnitTests.dll

test_script:
  - cd %BUILD_PATH%
  - IPC.Bond.UnitTests.exe --detect_memory_leaks=0 --log_level=test_suite
  - nunit3-console --framework=net-4.5 --labels=All IPC.Bond.Managed.UnitTests.dll --result=IPC.Bond.Managed.UnitTests.xml;format=AppVeyor
