version: 1.0.{build}

image: Visual Studio 2019

cache:
  - IPC\packages -> **\packages.config

# Use custom 'clone_script' instead of 'install' in order to run it before the cache from submodule is restored.
clone_script:
  ps: >-
    if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
  - git submodule update --init
  - cd bond
  - git submodule update --init thirdparty\rapidjson
  - cd ..

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BUILD_PATH: $(platform)\$(configuration)

install:
  - nuget restore IPC.Bond.sln

matrix:
  fast_finish: true

before_build:
  - bond.cmd %configuration% "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild IPC\IPC.sln /p:Configuration=%configuration% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  project: IPC.Bond.sln

test:
  assemblies:
  - $(BUILD_PATH)\IPC.Bond.Managed.UnitTests.dll

test_script:
  - cd %BUILD_PATH%
  - IPC.Bond.UnitTests.exe --detect_memory_leaks=0 --log_level=test_suite
  - nunit3-console --framework=net-4.5 --labels=All IPC.Bond.Managed.UnitTests.dll --result=IPC.Bond.Managed.UnitTests.xml;format=AppVeyor
